server:
  port: 8081
spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: d6f71a307039bd
    password: ba03df302887b8
    test-connection: true
  boot:
    admin:
      ui:
        brand: "<img src='assets/img/logo.png'><span>RandrinoDev</span>"
        title: 'Microservices Portal RandrinoDev'
        favicon: 'assets/img/logo.png'
        login-icon: 'assets/img/logo.png'
        available-languages:
          - fr
          - it
          - en
        view-settings:
          - name: 'about'
            enbled: false
      notify:
        mail:
          to:
            - nzeukangrandrin@gmail.com
          ignore-changes:
            - ''

